const stocks = [
  {
    id: 1,
    ticker: 'IKNX',
    company_name: 'Ikonics Corporation',
    market_cap: '$16.39M',
    market: 'NASDAQ',
    stock_sector: 'Miscellaneous',
  },
  {
    id: 2,
    ticker: 'BML^L',
    company_name: 'Bank of America Corporation',
    market_cap: 'n/a',
    market: 'NYSE',
    stock_sector: 'n/a',
  },
  {
    id: 3,
    ticker: 'MD',
    company_name: 'Mednax, Inc',
    market_cap: '$5.26B',
    market: 'NYSE',
    stock_sector: 'Health Care',
  },
  {
    id: 4,
    ticker: 'BWLD',
    company_name: 'Buffalo Wild Wings, Inc.',
    market_cap: '$2.24B',
    market: 'NASDAQ',
    stock_sector: 'Consumer Services',
  },
  {
    id: 5,
    ticker: 'SITE',
    company_name: 'SiteOne Landscape Supply, Inc.',
    market_cap: '$1.97B',
    market: 'NYSE',
    stock_sector: 'Consumer Non-Durables',
  },
  {
    id: 6,
    ticker: 'DCI',
    company_name: 'Donaldson Company, Inc.',
    market_cap: '$6.19B',
    market: 'NYSE',
    stock_sector: 'Capital Goods',
  },
  {
    id: 7,
    ticker: 'IO',
    company_name: 'Ion Geophysical Corporation',
    market_cap: '$50.45M',
    market: 'NYSE',
    stock_sector: 'Energy',
  },
  {
    id: 8,
    ticker: 'JXSB',
    company_name: 'Jacksonville Bancorp Inc.',
    market_cap: '$53.85M',
    market: 'NASDAQ',
    stock_sector: 'Finance',
  },
  {
    id: 9,
    ticker: 'CHKP',
    company_name: 'Check Point Software Technologies Ltd.',
    market_cap: '$18.26B',
    market: 'NASDAQ',
    stock_sector: 'Technology',
  },
  {
    id: 10,
    ticker: 'COT',
    company_name: 'Cott Corporation',
    market_cap: '$1.97B',
    market: 'NYSE',
    stock_sector: 'Consumer Non-Durables',
  },
];

module.exports = { stocks };
